<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSEbakY\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSEbakY/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXSEbakY.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXSEbakY\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXSEbakY\App_KernelProdContainer([
    'container.build_hash' => 'XSEbakY',
    'container.build_id' => 'deb0ceb0',
    'container.build_time' => 1642772685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSEbakY');
