<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1yiLjLS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1yiLjLS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1yiLjLS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1yiLjLS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1yiLjLS\App_KernelDevDebugContainer([
    'container.build_hash' => '1yiLjLS',
    'container.build_id' => '9024bdbf',
    'container.build_time' => 1643793404,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1yiLjLS');
