<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdmF0yu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdmF0yu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdmF0yu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdmF0yu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXdmF0yu\App_KernelDevDebugContainer([
    'container.build_hash' => 'XdmF0yu',
    'container.build_id' => '97270a1f',
    'container.build_time' => 1642189760,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdmF0yu');
