<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNCG1Jv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNCG1Jv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCNCG1Jv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNCG1Jv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCNCG1Jv\App_KernelDevDebugContainer([
    'container.build_hash' => 'CNCG1Jv',
    'container.build_id' => '4e5a662f',
    'container.build_time' => 1642770665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNCG1Jv');
